### ISSUE TITLE
Correction to README.md

### ISSUE THREAD

**Issue by PaleChantingGoshawk** [octokatherine/word-master#10]
No issues with the game.  But the README.md file should probably be fixed.  Currently, it's:

 * Green: The letter is correct, but in the wrong position.
 * Yellow: The letter is correct, in the correct position.
 * Gray: The letter is incorrect.

It should be:

 * Green: The letter is correct, in the correct position.
 * Yellow: The letter is correct, but in the wrong position.
 * Gray: The letter is incorrect.

**Comment by octokatherine** [comment]
Thank you for this! I'll fix. 

Kind of funny, GitHub Copilot actually suggested those instructions and I didn't proofread carefully
