### ISSUE TITLE
CTRL + SHIFT + R registers as a guess for the letter R

### ISSUE THREAD

**Issue by daniel-j-davis** [octokatherine/word-master#103]
Used CTRL + SHIFT + R to hard reload the page and saw "R" was detected as a guess on the first row. Should handleKeyDown ignore/return if event.ctrlKey is true maybe?

**Comment by octokatherine** [comment]
yeah i've noticed this, should probably be fixed 😄 it hasn't caused enough problems (you can always backspace) for me to prioritize it yet

**Comment by daniel-j-davis** [comment]
sounds good! was super easy to backspace to fix it, but was just reporting in case it wasn't known
