### ISSUE TITLE
Please add "clint" as an acceptable guess entry word

### ISSUE THREAD

**Issue by therudds8** [octokatherine/word-master#105]
Please add "clint" as an accepted Word Master guess entry.  Clint is a real English word (a hard or flinty rock : a rocky cliff : a projecting rock or ledge;  a crevice or gully in limestone rocks).  It is accepted in Wordle, is in the Miriam-Webster Dictionary, and is an accepted Scrabble word, but it is not an accepted guess entry in Word Master.  Is there a way to add it so that it is accepted by Word Master?  I would greatly appreciate it if you would.  BTW, I love Word Master (except for not having clint =).

**Comment by octokatherine** [comment]
Sure, I can add that
