### ISSUE TITLE
Coloring is off

### ISSUE THREAD

**Issue by rvarghese86** [octokatherine/word-master#119]
Number 36, Try kneel. The middle e should be yellow but is shown as gray.

**Comment by octokatherine** [comment]
what do you mean by number 36? what was the answer word?

**Comment by rvarghese86** [comment]
https://www.devangthakkar.com/wordle_archive/?36
The answer was unfed.
Sorry, I think I might have been wrong. I think this guy also misunderstood
coloring when two repeated letters are involved:
https://www.youtube.com/watch?v=fRed0Xmc2Wg

**Comment by octokatherine** [comment]
yeah, I think this is expected behavior. closing this out but let me know if you have any other questions!
