### ISSUE TITLE
Rejected Legitimate Words

### ISSUE THREAD

**Issue by RainEngineer** [octokatherine/word-master#135]
WordMaster frequently rejects legitimate words when operating in the Hard mode - these very  words are found acceptable in Normal mode.
Two examples are "PIXEL" and sometimes "RADIO".  Several other words have been found to fail.

**Comment by octokatherine** [comment]
Hard mode means you have to use any hints given so far in each subsequent guess. So all green letters you've been given must be used in the same spot, and yellow letters must be used. That is likely why those guesses are failing.

If you believe there is actually a bug, feel free to send a screenshot of a word being rejected in hard mode
