### ISSUE TITLE
Repeated letters don't function the same as Wordle

### ISSUE THREAD

**Issue by Costanza** [octokatherine/word-master#16]
Example: If I enter the word Fluffy, and the solution is Funky. Both "f" characters appear as yellow. Only one should, as there is only one "f" in the solution. In Wordle, two yellow "f" characters would represent the solution has two "f"s and both are currently in the wrong place.

**Comment by Sam0ht** [comment]
I had a look at this.  Guessing 'FLUFF' for 'FUNKY' works fine, as the first F is green and the last two are grey.  However guessing 'BLUFF' results in both the final letters being yellow, as you describe.

![image](https://user-images.githubusercontent.com/664835/147890008-10d683d3-2ec5-440f-bdd0-30b3e3d3d721.png)
