### ISSUE TITLE
Disallow selecting of letters on keyboard

### ISSUE THREAD

**Issue by octokatherine** [octokatherine/word-master#17]
![image](https://user-images.githubusercontent.com/49968061/147889958-116e8a8b-ef6f-4d3f-92a3-cbdbb8267788.png)

On touchscreens, it's easy to accidentally select the letters on the keys. They don't need to be selectable, so we should disable it

**Comment by kancherlakishorereddy** [comment]
👋 I made a PR for this issue. Check it out here PR #19 
- I've also hosted my fork [here](https://kancherlakishorereddy.github.io/word-master/), so you can easily see the fix working.
