### ISSUE TITLE
Seems like a blatant rip-off of wordle

### ISSUE THREAD

**Issue by mco-gh** [octokatherine/word-master#22]
- though the repo cites wordle, nowhere does that debt appear on the web game, which is what 90+% of people will see
- suggest changing "heavily inspired by" to "copy of"

**Comment by octokatherine** [comment]
I've talked to the creator of wordle to make sure he didn't have any issues with the game. 

I don't want to use the phrase "copy of" because it implies that it has all the features of Wordle which it does not (hard mode, sharing, etc). Also the format is different with it not being a daily game.

**Comment by mco-gh** [comment]
Fair enough about the "copy of" verbiage. But what about this point: "though the repo cites wordle, nowhere does that debt appear on the web game, which is what 90+% of people will see". Could you cite your source on the game page?

**Comment by mco-gh** [comment]
If you don't have time to do that, I'm happy to submit a PR.

**Comment by octokatherine** [comment]
Feel free to submit a PR

**Comment by mco-gh** [comment]
Done, thanks.
