### ISSUE TITLE
Wordlist has a bunch of strange words

### ISSUE THREAD

**Issue by h00701350103** [octokatherine/word-master#23]
Heya, lovely game!

I was just queried with "Leger" and neither me nor any of my friends had ever heard of it - and looking through various dictionaries on the internet they either don't have it, say it's a cubist painter, or some other weird stuff that no other dictionaries agree with (alternate spelling of ledger??).

I don't think super obscure words that are nigh impossible for a majority of people to guess should be generated as answers, and looking through `words.js` I'm seeing a lot of weird ones I would never be able to guess are real words. I'm not seeing a reference given to where you've got it from, but it'd maybe be nice to find a less obscure one? Either by finding one that's smaller and contains more common words, or cross-referencing a bunch of different ones and only take ones that are included in several.
I don't think the word list has to be huge in a game like this, since the same word can be arrived at through many different paths.

A possible issue is that one might want it to be more lenient in accepting guesses on words to make it easier to come up with words to guess, so one could have two wordlists - one with common words that are possible answers, and a larger one that are acceptable inputs. Downside of this is ofc that it might be slightly misleading and have people wasting guesses on words that can't be right.

Thanks,
h

**Comment by octokatherine** [comment]
Your suggestion in the last paragraph is exactly how it is implemented.

[words.js](https://github.com/octokatherine/word-master/blob/main/src/data/words.js) is used to check valid inputs, and [answers.js](https://github.com/octokatherine/word-master/blob/main/src/data/answers.js) is a much shorter list that I manually trimmed down to be reasonably guessable words. If you get a weird word, I just missed that one. Feel free to open a pull request removing the word from `answers.js`

**Comment by mumford2022** [comment]
I don't know how to open a pull request, but I just got the word LiDAR which is an acronym for Light Detection and Ranging. Seems like a good word to trim!

**Comment by octokatherine** [comment]
@mumford2022 just deleted it, thanks!
