### ISSUE TITLE
Click at end of game

### ISSUE THREAD

**Issue by RBskelton** [octokatherine/word-master#29]
Add click at end of game to allow user to review before jumping to streak.

**Comment by octokatherine** [comment]
To review, you can just close the "congrats" modal to look at it again. Then refresh the page to play again (you'll still keep your streak). We're working on adding something like a play again button on that screen instead of requiring the refresh.

let me know if you need any more help

**Comment by RBskelton** [comment]
Katherine -

First and foremost, thank you for building a version that one can play
multiple times per day, as one Wordle sometimes isn't enough. I love it.

I never would have figured out that you could close that modal by clicking
outside of it. I would suggest adding an "x" to the upper right of the
modal to close it. I probably eventually would have figured out the
refresh, but adding a play again option is a brilliant idea.

Thanks again!

Marc
