### ISSUE TITLE
Allow user to reveal the answer

### ISSUE THREAD

**Issue by defyentropy** [octokatherine/word-master#30]
I've been playing the game for a while now, and sometimes, at the end, I'm stuck with a few uncommon letters and only a few confirmed letters. There's no way to end the game except to find the correct word or to guess any word (which is actually quite difficult because the letters aren't very common). It would be great if there was a way to manually end the game and reveal the answer, so the player can learn from their mistakes. This would, obviously, end the player's streak.

For example, here's a recent game where it happened:
![image](https://user-images.githubusercontent.com/63222497/148375888-a39f2087-cf21-420f-9209-d6922c51672d.png)

As you can see, finding a word with QWYFJZXVOG isn't easy.

**Comment by defyentropy** [comment]
If you think this is a good idea, I would be happy to submit a PR.

**Comment by octokatherine** [comment]
to end the game you can just guess any word with any letters. like you could just type in "drums" again. does that help? @defyentropy

**Comment by chynnakeys** [comment]
I think it’s foggy :)

**Comment by defyentropy** [comment]
> to end the game you can just guess any word with any letters. like you could just type in "drums" again. does that help? @defyentropy 

OK yes, that makes sense. Thank you for clearing that up. I guess I was so preoccupied with trying to find the right answer that I forgot you could reuse grayed-out letters.
