### ISSUE TITLE
Create new reveal color when letter is in the word multiple times 

### ISSUE THREAD

**Issue by chynnakeys** [octokatherine/word-master#35]
If a new color could pop up when the letter is in the word more than once that would be great!

**Comment by imfarhanaslam** [comment]
hello @chynnakeys  can i do this please if you guide bit more on this?

**Comment by octokatherine** [comment]
hm, i've heard mixed opinions on this and I actually think it's a nice part of the challenge of the game. 

I'm going to close this out for now, but if you want to keep discussing, feel free to bring it up over in the discussion tab of the repo
