### ISSUE TITLE
Full Screen View while playing, shouldn't scrolled vertically 

### ISSUE THREAD

**Issue by imfarhanaslam** [octokatherine/word-master#36]
I wish to have full game view in full screen without scrolling down, currently letters are below and we need to scroll each time up and down while playing.

**Comment by octokatherine** [comment]
@imfarhanaslam what size device are you playing on?

**Comment by imfarhanaslam** [comment]
> 

MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by octokatherine** [comment]
hm it surprises me that that is happening on that device. would you mind posting a screenshot?

**Comment by scottBowles** [comment]
<img width="1440" alt="Screen Shot 2022-01-07 at 7 15 06 PM" src="https://user-images.githubusercontent.com/59491167/148622814-c1f1ece0-0d95-4dcc-9c10-b48e6343b6ad.png">
Here it is on a 2020 13" MacBook Pro. With the bookmark bar the bottom row of the keyboard is covered, but going to 90% zoom fixes in both cases. Thanks for this game btw. It is great!

**Comment by imfarhanaslam** [comment]
> hm it surprises me that that is happening on that device. would you mind posting a screenshot?
<img width="1440" alt="Screen Shot 2022-01-08 at 10 12 45 AM" src="https://user-images.githubusercontent.com/18443687/148632437-1d151b1b-086f-4f24-b786-80712931369a.png">

**Comment by octokatherine** [comment]
hm yeah it seems like it might have to do with zoom level. I'm not sure this should be a code change, maybe try zooming out a bit? on a mac you can press `cmd -`
