### ISSUE TITLE
Possible colour problem

### ISSUE THREAD

**Issue by billtubbs** [octokatherine/word-master#46]
thanks, great work!

I’m new to this game but shouldn’t the colour of the ‘e’s on the second row be the same?

<img width="768" alt="Screenshot 2022-01-10 at 19 38 52" src="https://user-images.githubusercontent.com/7958850/148877979-542a3b9f-04eb-40ec-b1b8-d88da3396c88.png">

**Comment by billtubbs** [comment]
Duh.  Of course not!

**Comment by billtubbs** [comment]
Sorry I meant to attach this screenshot:

<img width="768" alt="Screenshot 2022-01-10 at 19 34 22" src="https://user-images.githubusercontent.com/7958850/148878447-602aeb73-715b-4c0d-816e-fe90727d664c.png">

same question.

**Comment by octokatherine** [comment]
@billtubbs nope, what it means is that there is only 1 e in the solution! neither spot is correct. if they were both yellow, it would mean there are 2 e's

**Comment by billtubbs** [comment]
I see thanks for explaining.  So it means there is one e but not in either of these positions? Thanks.

**Comment by octokatherine** [comment]
yep! no problem. 

it's a bit confusing, in my original logic both e's would have been yellow even if there was only 1 in the solution, but then people thought that meant there were 2 in the solution and got confused. 

there are flaws in both approaches haha
