### ISSUE TITLE
"gyoza" is probably an excessively difficult word

### ISSUE THREAD

**Issue by boergens** [octokatherine/word-master#52]
https://github.com/octokatherine/word-master/blob/main/src/data/answers.js#L895

**Comment by octokatherine** [comment]
haha, I kind of disagree here actually, but the list is totally biased to how well I know words. would be curious to hear more thoughts on this one. 

I'm hesitant to remove a word every time someone requests a removal, because we could really whittle down the list that way

**Comment by boergens** [comment]
Fair enough :-)

**Comment by boergens** [comment]
I guess everybody has different words they are familiar with :-)
Google Ngram viewer would be a good way to objectivize this.
For example this could be seen as evidence that "drake" should replace "deked" in the list of possible answers:
https://books.google.com/ngrams/graph?content=deked%2Cdrake%2Cgyoza&year_start=1800&year_end=2010&corpus=0&smoothing=3&direct_url=t1%3B%2Cdeked%3B%2Cc0%3B.t1%3B%2Cdrake%3B%2Cc0%3B.t1%3B%2Cgyoza%3B%2Cc0#t1%3B%2Cdeked%3B%2Cc0%3B.t1%3B%2Cdrake%3B%2Cc0%3B.t1%3B%2Cgyoza%3B%2Cc0

I'll look into this a bit more to see whether I can create a list of "difficult" words and potential replacements

**Comment by boergens** [comment]
I added some more words than I removed, this would be the next batch of potential deletion candidates (frequency between 0.000000007 and 0.000000017)

abash
bundt
cakey
ditsy
doggo
duffs
easer
frier
fudgy
gabby
gnarl
gyoza
hypes
icier
lacey
okays
snark
syren
tases
taxer
unpin
yappy

**Comment by octokatherine** [comment]
would you want to open a PR with those changes?

**Comment by octokatherine** [comment]
ah just noticed you did, thank you! merged.

**Comment by boergens** [comment]
some more inclusion candidates for future reference
https://gist.github.com/boergens/e520d4ca9205722a90f54f14193e44dd
