### ISSUE TITLE
Persistent answer after 6 wrong guesses

### ISSUE THREAD

**Issue by mrprajesh** [octokatherine/word-master#56]
Thanks for the unlimited Wordle games.

Suggestion: Suppose I have exhausted all the 6 guesses and then the answer (probably it is a *new* word for me) appears on the new screen. I had to `ESC` to see my guesses when investigating what I could have done better. Many times, I forget the spelling of that _new word_. It will be nice if the answer stays there along with our guesses like in Wordle. 

Thanks,
Rajesh.

**Comment by teleshoes** [comment]
(not saying youre wrong, but as a workaround, you can now just refresh the browser and get the popup back)

**Comment by octokatherine** [comment]
yeah, for now I would just go with the workaround mentioned above
