### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by schferbe** [octokatherine/word-master#57]
There is a considerable amount of forks around that mainly update the words to another language. For example forks for Greek, Hebrew, Somali, German and other languages exist. Not all of these forks are playable by everybody as they have not set up Github pages.

Would it be possible to add multiple word and answer files and make the language selectable at the start?

**Comment by octokatherine** [comment]
That's not a bad idea, but honestly I think I would prefer people host their own forks because I don't have the bandwidth for the extra maintenance. 

I already get a lot of requests for additions/removals on the English word list, and I wouldn't be able to make those decisions for other languages.
