### ISSUE TITLE
error in answers -- word was "quirk" but i and r were green  in positions 2 and 3 for several tries

### ISSUE THREAD

**Issue by leucothoe** [octokatherine/word-master#60]

**Comment by octokatherine** [comment]
if you could provide a screenshot that would be helpful. I haven't seen reports of answer errors and hundreds of thousands of people have played

**Comment by leucothoe** [comment]
Hi -- realise now it was my mistake: "ir" in 2 and 3 were yellow not green,
word was "quirk"....sorry! feeling pretty stupid....really enjoy the game
so thanks! can you delete my issue as it was not an issue -- don't know how
github works...
