### ISSUE TITLE
Very hard guesses when words are similar

### ISSUE THREAD

**Issue by boergens** [octokatherine/word-master#61]
The below is a bit of a feelbad and should be mitigated

**Comment by boergens** [comment]
![image](https://user-images.githubusercontent.com/1429753/149431214-71d90cf7-7914-46bd-9e28-7f0f9375bb69.png)

**Comment by octokatherine** [comment]
I disagree here, to me this is part of the challenge. 

the strategy in a situation like this is to not keep guessing the letters you already know. instead, take all the possibilities and guess a word with those (like "wheat" in this case to test the w, h, and t.)

**Comment by boergens** [comment]
I definitely understand where you are coming from. But if one prefers to play in "hard mode" (as defined by Wordle), that's not possible.
