### ISSUE TITLE
Red circles

### ISSUE THREAD

**Issue by ConchoMama** [octokatherine/word-master#64]
I love this game but several times have encountered red circles around all 5 letters in a single attempt. What does that mean? 
![17DAEB97-33AF-4AD8-9F77-A8DF1CCEE2BA](https://user-images.githubusercontent.com/97767397/149597443-85417469-d98c-4423-babd-c7266dfff8e4.png)

**Comment by octokatherine** [comment]
it means it's not a valid word. should be `niece` :) I have meant to add a little popup that says "invalid word" to make this more clear.

**Comment by octokatherine** [comment]
opened up [a new issue](https://github.com/octokatherine/word-master/issues/65) for making this more clear. thanks!

**Comment by ConchoMama** [comment]
Thanks! That is what we suspected but some of the words were valid…at least we thought so! 😉 
I have now addicted my mother to this game! She is 81 and mostly blind but the “dark” feature allows her to see the letters so thanks for adding that!
Tami

**Comment by ckjpn** [comment]
I know that you've closed this, but the same thing confused me at first.
Perhaps you could add a note about this in your instructions.

Perhaps the following will prompt a good wording in your brain.

If after entering a word, you see all 5 letters circled in red, then the word is invalid.
