### ISSUE TITLE
App going beyond one screen on desktop and mobile

### ISSUE THREAD

**Issue by lauriebatchelor** [octokatherine/word-master#69]
Some potential versions have been made to rectify this.  Initial discussion at: https://github.com/octokatherine/word-master/pull/67. 

1. @teleshoes version at: https://fir-word-master.web.app/.  The keyboard for this is too small on my mobile and I make typing errors unless I'm being careful.

2. My version at: https://fir-word-master-2.web.app/. @teleshoes said the words in this version were very small on their laptop and tablet.

Would be good if others were able to have a look at both to see if they encounter any of the same problems

**Comment by teleshoes** [comment]
maybe you should open another pr with some kind of combined soln? one that makes the keyboard as large as your soln, but also resizes the fonts as the screen gets bigger/smaller (like wordle)
