### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by octokatherine** [octokatherine/word-master#7]
Dark mode! 

Two alternatives I'd be okay with here:

a. Always default to the user's browser theme preference
b. Default to light mode, when the user changes it save their preference to local storage

**Comment by kancherlakishorereddy** [comment]
👋 hey, I want to work on this. But I can't figure out a good-looking color palette for dark mode.

**Comment by octokatherine** [comment]
ah yeah. maybe @noelsner can provide some advice? he did the original styles

**Comment by noelsner** [comment]
I agree, the dark mode color palette is tough 😬
I would go with a dark-gray background color like [this](https://dribbble.com/shots/11652074-FREE-Neumorphism-UI-Kit) and then the yellow, green, and gray colors might be able to stay the same (I think those colors are in HSL formats so you could play with lightness percentages to see if darker versions of those colors look better)
