### ISSUE TITLE
Repeating letter in answer (eg H in HUNCH) notified in YELLOW plus GREEN

### ISSUE THREAD

**Issue by DrJohnDavis** [octokatherine/word-master#71]
If the answer word has a repeating letter (e.g. MUMMY, PUPPY, HUNCH, CIRCA) there is a confusion for the user if they guess only one of the letters in the correct position.

If only one of multiple instances of same letter is correct in the guess, let us make it green in the table(because it is correct), but yellow in the keyboard(because it is incomplete)

Sounds like a reasonable addition ?

**Comment by octokatherine** [comment]
@DrJohnDavis @ZachEdwards7, I'd actually rather leave this as is, I think it would be too big of a hint to tell the user that the letter is used again when they've only guessed it once.
