### ISSUE TITLE
Easier Word List for the Default Game

### ISSUE THREAD

**Issue by ckjpn** [octokatherine/word-master#80]
## The problem

Words like the following, which are currently part of the game, are not in a lot of native speakers' active or even perhaps passive vocabulary, so the game may not be so fun, and would be particularly difficult for children and those speaking English as a non-native language.

aahed, aalii, aargh, abaca, abaci, aback, abaft, abaka, abamp,, abaya, abbas, abbes, abele, ables, abmho, abohm, aboil, aboma, aboon, abris, abuts, ...

## A possible solution

To keep this more game-like, with more successes, limit the words to higher-frequency words.

## A possible list

Here is a possible list of words.

Though a much lower number of words, there should still be enough words to make it challenging and fun.

I choose these words from the headwords of the NGSL. (http://www.newgeneralservicelist.org/)

This list could be expanded by adding the other words in the same "word family" for each of these.

File 1: 468 words - All are headwords from the NGSL
File 2: 603 words - An additional list with some words in the same word families.  Note that this would need to be cleaned up a bit because it contains items such as weren (from weren't), haven (from haven't), and maybe more.

[NGSL 5-letter words.zip](https://github.com/octokatherine/word-master/files/7893440/NGSL.5-letter.words.zip)

**Comment by octokatherine** [comment]
@ckjpn 

> aahed, aalii, aargh, abaca, abaci, aback, abaft, abaka, abamp,, abaya, abbas, abbes, abele, ables, abmho, abohm, aboil, aboma, aboon, abris, abuts, ...

none of those words are in [the answer list](https://github.com/octokatherine/word-master/blob/main/src/data/answers.js).

That list has already been manually filtered down to common words. If there are specific words from that list that you think should be removed, you can open an issue or PR.

**Comment by ckjpn** [comment]
Sorry, I misunderstood the code.

I think I got it working OK on my one website now, limited to the first 250 five-letter words on the NGSL.

http://www.manythings.org/wm/

I misunderstood the words at Se = { ....
And, now realize it's the we = [ ... words that are the answers.

Thanks for making this open source and using teh MIT license.

**Comment by ckjpn** [comment]
Here are a couple of other levels.

http://www.manythings.org/wm2/
Limited to 134 5-letter words found on a Junior High School word list. (What Japanese JHS students learn.)

http://www.manythings.org/wm3/
594 five-letter words from NGSL, including some of related words in the word families.

Once you've seen these, please delete this message and the earlier one with my URL, since I'm not sure if I should really make them publicly available yet.

Instead of this way of doing it, it would likely be better to have the different levels in their own external .js files and load in the different levels that way.  I don't have time to look into that now.

Thanks once again.
