### ISSUE TITLE
Roate 

### ISSUE THREAD

**Issue by KylieMJ** [octokatherine/word-master#88]
Fun game! Thanks for making it. 

On 13th screen in streak, game wouldn’t accept the correct answer, roate. I posted screenshots.

**Comment by KylieMJ** [comment]
![4E900E46-4972-443B-A64F-7C38BC996FBD](https://user-images.githubusercontent.com/98213206/150635094-1471fada-11d6-4be1-a66a-3fd167291d3b.png)
![3F45B7F8-ED1B-4A06-9BB7-95AB464AF5C6](https://user-images.githubusercontent.com/98213206/150635097-c5eefc4d-6f0b-44eb-a4c9-fc6139317807.png)
![BA5498DC-FF10-4D95-A02A-1E5F4B826DE7](https://user-images.githubusercontent.com/98213206/150635098-1c608b65-588d-4404-84bf-c7d1867bae85.png)
![5063F8DE-4CC7-4A3D-B35D-C45BF9C00226](https://user-images.githubusercontent.com/98213206/150635099-9ee99234-4562-4c13-9a02-ba2b8eefd0a8.png)

**Comment by octokatherine** [comment]
thanks for the report, I added it to the valid word lists and removed it from the possible answers list
